name: Build ImGuiRedux
on: push
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [Win32, Win64]
        buildtype: [Release, ReleaseCleo]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup premake
        uses: abel0b/setup-premake@v2
        with:
          version: "5.0.0-beta1"
      - name: Configure build
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.platform}} 
      - name: Build plugin
        run: |
          cd tools
          premake5 vs2022
          cd ../build
          MsBuild ImGuiRedux.sln /property:Configuration=${{matrix.buildtype}} /p:Platform=${{matrix.platform}} /t:ImGuiRedux
      - name: Upload plugin
        uses: actions/upload-artifact@v3
        with:
          name: ImGuiRedux${{matrix.platform}}
          path: build\bin\ImGuiRedux${{matrix.platform}}.cleo
      - name: Archive plugin
        uses: papeloto/action-zip@v1
        with:
          files: build\bin\ImGuiRedux${{matrix.platform}}.cleo
          dest: ImGuiRedux${{matrix.platform}}.zip
      - name: Add build to release tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: ImGuiRedux${{matrix.platform}}.zip
          name: "ImGuiRedux ${{matrix.platform}}"
          body: "ImGuiRedux for ${{matrix.platform}}. This release is updated regularly"
          allowUpdates: true
          tag: "${{matrix.platform}}-latest"
        
