name: Build ImGuiRedux
on: push
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [Win32, Win64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup premake
        uses: abel0b/setup-premake@v2
        with:
          version: "5.0.0-beta1"
      - name: Configure build
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.platform}} 
      - name:  Configure envs
        run:   echo ::set-env name=DXSDK_DIR::$HOME/cache/
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        shell: bash
      - name: Cache DX SDK
        id:   cache
        uses: actions/cache@v1
        with:
          path: ~/cache
          key:  cache
      - name:  Cache create DX SDK
        if:    steps.cache.outputs.cache-hit != 'true'
        run:   |
              curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o _DX2010_.exe
              7z x _DX2010_.exe DXSDK/Include -o_DX2010_
              7z x _DX2010_.exe DXSDK/Lib/x86 -o_DX2010_
              mv _DX2010_/DXSDK $HOME/cache
              rm -fR _DX*_ _DX*_.exe
        shell: bash
      - name: Build plugin
        run: |
          cd tools
          premake5 vs2022
          cd ../build
          MsBuild ImGuiRedux.sln /property:Configuration=Release /p:Platform=${{matrix.platform}} /t:ImGuiRedux
      - name: Upload plugin
        uses: actions/upload-artifact@v3
        with:
          name: ImGuiRedux${{matrix.platform}}
          path: build\bin\ImGuiRedux${{matrix.platform}}.cleo
      - name: Archive plugin
        uses: papeloto/action-zip@v1
        with:
          files: build\bin\ImGuiRedux${{matrix.platform}}.cleo
          dest: ImGuiRedux${{matrix.platform}}.zip
      - name: Add build to release tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: ImGuiRedux${{matrix.platform}}.zip
          name: "ImGuiRedux ${{matrix.platform}}"
          body: "ImGuiRedux for ${{matrix.platform}}. This release is updated regularly"
          allowUpdates: true
          tag: "${{matrix.platform}}-latest"
        
