name: Build ImGuiRedux
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup premake
        uses: abel0b/setup-premake@v2
        with:
          version: "5.0.0-beta1"
      - name: Configure build
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: Win32 
      - name: Build plugin
        run: |
          cd tools
          premake5 vs2022
          cd ../build
          MsBuild ImGuiRedux.sln /property:Configuration=Release /p:Platform="Win32" /t:ImGuiRedux
      - name: Upload plugin
        uses: actions/upload-artifact@v3
        with:
          name: ImGuiRedux
          path: build\bin\ImGuiRedux.cleo
      - name: Archive plugin
        uses: papeloto/action-zip@v1
        with:
          files: build\bin\ImGuiRedux.cleo
          dest: ImGuiRedux.zip
      - name: Add build to release tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: ImGuiRedux.zip
          name: "ImGuiRedux Latest"
          body: "Secondary tag for [this release](https://github.com/user-grinch/ImGuiRedux/releases/latest) of ImGuiRedux. This release is updated regularly"
          allowUpdates: true
          tag: "x86-latest"
        
